site_name: API English Glossary
site_url: https://maccana.github.io/api-english-portal/

theme:
  name: material
  palette:
    scheme: slate
    
plugins:
  - search
  - blog:
      post_dir: blog/posts
      blog_dir: blog
      # We are removing authors_file to use the internal 'extra' map instead
      
extra:
  blog:
    authors:
      mike:
        name: Mike McCann
        url: https://github.com/maccana
        avatar: https://github.com/maccana.png

nav:
  - Home: index.md
  - Blog: blog/
  - Pipeline Test: test2.md