site_name: API English Glossary
site_description: Documentation and coaching for API Technical Writing.
site_url: https://your-username.github.io/cicd-test/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - content.code.copy

plugins:
- blog:
      post_dir: blog/posts
      blog_dir: blog
      authors_file: authors.yml  # <--- This is the key change
      

nav:
  - Home: index.md
  - Blog: 
    - blog/index.md
  - Pipeline Test: test2.md