site_name: API English Glossary
site_url: https://maccana.github.io/api-english-portal/

theme:
  name: material
  palette:
    scheme: slate

extra:
  blog:
    authors:
      mike:
        name: Mike McCann
        url: https://github.com/maccana
        avatar: https://github.com/maccana.png

plugins:
  - search
  - blog:
      post_dir: blog/posts
      blog_dir: blog

nav:
  - Home: index.md
  - Blog: blog/index.md   # <--- Point directly to the file
  - Pipeline Test: test2.md