authors:
  mike:
    name: Mike McCann
    description: Technical writer and IT English Coach
    url: https://github.com/maccana
    avatar: https://github.com/maccana.png 
  guest:
    name: Guest
    description: Guest Writer
    url: https://github.com/maccana
    avatar: https://github.com/maccana.png   